MySQLDatabase:
  Type: "AWS::RDS::DBCluster"
  Properties:
    Engine: aurora
    EngineMode: serverless
    EngineVersion: "5.6.10a"
    Port: 3306
    DatabaseName: {{cluster.databaseName}}
    DBClusterIdentifier: {{cluster.id}}
    MasterUsername: "{{cluster.masterUsername}}"
    MasterUserPassword: "{{cluster.masterUserPassword}}"
    DeletionProtection: false
    DBSubnetGroupName: {{cluster.subnetName}}
    AvailabilityZones:
      "Fn::Split": [",", {"Ref": AvailabilityZones}]
    VpcSecurityGroupIds:
      "Fn::Split": [",", {"Ref": SecurityGroups}]
    BackupRetentionPeriod: {{cluster.backupTTL}}
    PreferredBackupWindow: {{cluster.backupWindow}}
    PreferredMaintenanceWindow: {{cluster.maintenanceWindow}}
    {{#if cluster.kmsKey}}
    KmsKeyId: {{cluster.kmsKey}}
    StorageEncrypted: true
    {{/if}}
    ScalingConfiguration:
      AutoPause: true
      MinCapacity: {{cluster.capacity.min}}
      MaxCapacity: {{cluster.capacity.max}}
      SecondsUntilAutoPause: 21600  # 6 Hours
    Tags:
      {{#each tags}}
      - Key: {{Key}}
        Value: {{Value}}
      {{/each}}
